application: plated-analyzer-117711
version: 1
runtime: go
api_version: go1

default_expiration: "30d"

skip_files:
- "^(.*/)?#.*#$"
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^/\.git/.*
- ^/letsencrypt/.*
- ^/source/.*
- ^/content/.*

handlers:
- url: /(.*\.(appcache|manifest))
  mime_type: text/cache-manifest
  static_files: public/\1
  upload: public/(.*\.(appcache|manifest))
  expiration: "0m"

- url: /(.*\.atom)
  mime_type: application/atom+xml
  static_files: public/\1
  upload: public/(.*\.atom)
  expiration: "1h"

- url: /(.*\.crx)
  mime_type: application/x-chrome-extension
  static_files: public/\1
  upload: public/(.*\.crx)

- url: /(.*\.css)
  mime_type: text/css
  static_files: public/\1
  upload: public/(.*\.css)

- url: /(.*\.eot)
  mime_type: application/vnd.ms-fontobject
  static_files: public/\1
  upload: public/(.*\.eot)

- url: /(.*\.htc)
  mime_type: text/x-component
  static_files: public/\1
  upload: public/(.*\.htc)

- url: /(.*\.html)
  mime_type: text/html
  static_files: public/\1
  upload: public/(.*\.html)
  expiration: "1h"

- url: /(.*\.ico)
  mime_type: image/x-icon
  static_files: public/\1
  upload: public/(.*\.ico)
  expiration: "7d"

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: public/\1
  upload: public/(.*\.js)

- url: /(.*\.json)
  mime_type: application/json
  static_files: public/\1
  upload: public/(.*\.json)
  expiration: "1h"

- url: /(.*\.m4v)
  mime_type: video/m4v
  static_files: public/\1
  upload: public/(.*\.m4v)

- url: /(.*\.mp4)
  mime_type: video/mp4
  static_files: public/\1
  upload: public/(.*\.mp4)

- url: /(.*\.(ogg|oga))
  mime_type: audio/ogg
  static_files: public/\1
  upload: public/(.*\.(ogg|oga))

- url: /(.*\.ogv)
  mime_type: video/ogg
  static_files: public/\1
  upload: public/(.*\.ogv)

- url: /(.*\.otf)
  mime_type: font/opentype
  static_files: public/\1
  upload: public/(.*\.otf)

- url: /(.*\.rss)
  mime_type: application/rss+xml
  static_files: public/\1
  upload: public/(.*\.rss)
  expiration: "1h"

- url: /(.*\.safariextz)
  mime_type: application/octet-stream
  static_files: public/\1
  upload: public/(.*\.safariextz)

- url: /(.*\.(svg|svgz))
  mime_type: images/svg+xml
  static_files: public/\1
  upload: public/(.*\.(svg|svgz))

- url: /(.*\.swf)
  mime_type: application/x-shockwave-flash
  static_files: public/\1
  upload: public/(.*\.swf)

- url: /(.*\.ttf)
  mime_type: font/truetype
  static_files: public/\1
  upload: public/(.*\.ttf)

- url: /(.*\.txt)
  mime_type: text/plain
  static_files: public/\1
  upload: public/(.*\.txt)

- url: /(.*\.unity3d)
  mime_type: application/vnd.unity
  static_files: public/\1
  upload: public/(.*\.unity3d)

- url: /(.*\.webm)
  mime_type: video/webm
  static_files: public/\1
  upload: public/(.*\.webm)

- url: /(.*\.webp)
  mime_type: image/webp
  static_files: public/\1
  upload: public/(.*\.webp)

- url: /(.*\.woff)
  mime_type: application/x-font-woff
  static_files: public/\1
  upload: public/(.*\.woff)

- url: /(.*\.xml)
  mime_type: application/xml
  static_files: public/\1
  upload: public/(.*\.xml)
  expiration: "1h"

- url: /(.*\.xpi)
  mime_type: application/x-xpinstall
  static_files: public/\1
  upload: public/(.*\.xpi)

# image files
- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: public/\1
  upload: public/(.*\.(bmp|gif|ico|jpeg|jpg|png))

# audio files
- url: /(.*\.(mid|midi|mp3|wav))
  static_files: public/\1
  upload: public/(.*\.(mid|midi|mp3|wav))

# windows files
- url: /(.*\.(doc|exe|ppt|rtf|xls))
  static_files: public/\1
  upload: public/(.*\.(doc|exe|ppt|rtf|xls))

# compressed files
- url: /(.*\.(bz2|gz|rar|tar|tgz|zip))
  static_files: public/\1
  upload: public/(.*\.(bz2|gz|rar|tar|tgz|zip))

# letsencrypt challenges
- url: /(\.well-known/acme-challenge/.*)
  script: letsencrypt
  secure: optional  # These need to be able to be HTTP for bootstrapping.

# URL redirector
- url: /go/(.*)
  script: redirect
  secure: always

# index files
- url: /(.+)/
  static_files: public/\1/index.html
  upload: public/(.+)/index.html
  expiration: "2m"
  secure: always

- url: /(.+)
  static_files: public/\1/index.html
  upload: public/(.+)/index.html
  expiration: "2m"
  secure: always

- url: /(.*/index\.xml)
  mime_type: application/atom+xml
  static_files: public/\1
  upload: public/(.*\.xml)
  expiration: "1h"

# site root
- url: /
  static_files: public/index.html
  upload: public/index.html
  expiration: "2m"
  secure: always
